name: release

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
    inputs:
      version:
          description: 'Version to release'
          required: true
          default: 'v0.0.0'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: ui/package.json
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
        cache: true
    - name: Build UI
      run: |
        make setup-ui
        make build-ui
    - name: Build Backend
      run: |
        make build-backend
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./bin/rancher-rbac-wizard
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
